language: php
php:
- 5.6
- 7.0
before_script:
- composer self-update
- echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
- phpenv config-rm xdebug.ini
- composer install --no-interaction --prefer-dist
- php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
script:
- php vendor/bin/parallel-lint --exclude vendor .
- php vendor/bin/phpcs --standard=vendor/mygento/coding-standard/Mygento-Mage2 .
- php vendor/bin/phpmd . text cleancode,codesize,design,naming,unusedcode vendor/mygento/coding-standard/Mygento-Mage2/phpmd.xml --exclude vendor
env:
  global:
  - secure: g7EPHcgGCAoGvZvWpi4ELmzuTNA/7UwU0YN8mazk1bem/Ykmva/zOOwGCe2brNgYTZTpXjr95Y8F6/6ITMvpR1NJEeGHUbB5HdwhvR/OM6BK5sR1Rc6FZTFdadSwGYpMpflNrDZOkAQahf7xFz7JqmAg3VAGZ11Y7VHeNfh4LHLSfu0W7E5dRkF4qmgo/cGFcenogTwhr3bhBAy6QJTQdU9QQ+TtcZDN0lmZXhYYbd1cxAw7KQrOkos4/4yS5H2Kx4YUWCMUn1asL5sXTSjDSvRZqgvboCn/92Sluc/k3RR8vhC8A91r+siuMoGlRxDVFJClkFGzW//1GCG879Ly8Oq8lcNGS5SCPG14fAk0V0So30cv2DgVpONiXcvzNfFPIA8zVyhv53FmGDj2TlEVuDmU7Rhp+SpxABK8ohq/HHi1kl1gNrvu+dHnGXvVSb7ziLGJSYFTJl54fUoG3oI44n1bkjgKOjR4oC6w8DDzje722f2kxg/uYJKCrY8i3/IZSacG4rhPV7Wxtf8X51nQA7kHzMjXFAuCHeXAuFZYl642lEakt/PmJ1jz7+cKQ0F3zKk+rfSnQXaxLJ6vQSMkKFx9kZnFu9sSYQAlO7qVKYS7/867GpESso5eteBCuFcJlmS3sAPj7AnWH/PFfTMhRN0/MuNiPfCzpuW2U0BB0AY=
  - secure: QdBGe8O/M63LzIZwi0lNf8e8h+XKjuA6t0aVU3WdkOZ1/Q9FMa1/jYFhOMq1YLU7AMUsAX34ZbvA/qxC3J+41THbF9+2rL+dVdgQYL4rd41ttdSTAEBmRNasAP2K8gRkCOMoGBThjSE3uVMwzNMKWarspJ97r/jpgthKzk2S//sSWRcy02sifo+xGy7mfzb/0ZKbJdSBqM453tJ1cTRFkgCmfP+32yPsvCa949rlLaXCR1malABhhbNDU2XQ5wyyad6QQ5JwTSU55mbtxcUXXVhOJmGIZEnBlrrxIslR6yHI3fB/k9ks5I1CdGuFQkocQP0AlWVYjqWQxEL4E5/dDtdaWEvwzZMiGxxetS7oW102N23zwOXOkGdsMUbuTATUNWSb2fL5faontcYL1ISw3gfzVFs9meJX+gIzf6+s+Rd6kJHFTO7ThG22LR99nB8ul/FlT6jWPTeXUGli1oVV/asR1LlYL7CiwWkTaP01fEVkp3BSR10xVBBCvqd9JwUaJHVhvKP4yq+MjwNWDeOO+pFxXZP57dKPrXlmGeObNIPqiZH2odLsdpVCh1kQIhjeqbo41pg8xVoQAntCfcBWpqBZGN6qNEJR40dBrzdjKT+TwOQmjTxv/EQbnUGUwS+yR8erQbbsAQjXhy1urn9nEvLbklVRan1xm5R6ZsY2OQ4=
